{{ if .Values.config.sealedsecret.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nsupdate-operator-secret
  namespace: {{ .Values.namespace.name }}
spec:
  encryptedData:
    KEY: {{ .Values.config.sealedsecret.masterKey }}
  template:
    metadata:
      name: nsupdate-operator-secret
      namespace: {{ .Values.namespace.name }}
    type: Opaque
---
{{ if and .Values.config.webhook.enabled -}} 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nsupdate-operator-certs
  namespace: {{ .Values.namespace.name }}
spec:
  encryptedData:
    key: {{ .Values.config.sealedsecret.webhookCertificate.key }}
    server: {{ .Values.config.sealedsecret.webhookCertificate.server }} 
  template: 
    metadata:
      name: nsupdate-operator-certs
      namespace: {{ .Values.namespace.name }}
    type: Opaque
{{- end }}

{{ end }}