{{ if .Values.config.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nsupdate-operator-secret
  namespace: {{ .Values.namespace.name }}
stringData:
  KEY: {{ .Values.config.secret.masterKey }}
type: Opaque
---
{{ if and .Values.config.webhook.enabled -}} 
apiVersion: v1
kind: Secret
metadata:
  name: nsupdate-operator-certs
  namespace: {{ .Values.namespace.name }}
stringData:
  server: |+
{{ .Values.config.secret.webhookCertificate.server | indent 4 }}
  key: |+
{{ .Values.config.secret.webhookCertificate.key | indent 4 }}
type: Opaque
{{- end }}

{{- end }}