apiVersion: v1
kind: Service
metadata:
  name: admission
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: admission
  selector:
    app: nsupdate-operator-dnsr